function runHistory
clc, clear, close all

%-- choose task to perform 
itask=3; % 1 to 3 (see task options below)

%-- task options
tasks={
    'x_vs_D'; % steady state relationship between x and D (Fig. 2)
    'resilience'; % Fig. 4 (Fig. 3 can also be generated by properly adjusting the parameters as described in the paper)
	'hysteresis'; % Fig. 5 
    };
task=tasks{itask};

%-- perform the chosen simulation task 
goSimulation(task)
